services:
  localstack:
    container_name: ticket-booking-aws
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # Gateway do LocalStack
      - "127.0.0.1:4510-4559:4510-4559"  # Serviços externos
    environment:
      - SERVICES=dynamodb,sqs,stepfunctions,sts,iam
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./infra:/etc/localstack/init/ready.d" # Mapeia a pasta de scripts
      - "/var/run/docker.sock:/var/run/docker.sock"
