services:
  localstack:
    container_name: ticket-booking-aws
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,sqs,stepfunctions,sts,iam
      - DEBUG=1
      - AWS_DEFAULT_REGION=sa-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./setup-aws.sh:/etc/localstack/init/ready.d/setup-aws.sh"
      - "./workflow-definition.json:/etc/localstack/init/ready.d/workflow-definition.json"

  keycloak:
    container_name: ticket-booking-auth
    image: quay.io/keycloak/keycloak:26.1.0
    volumes:
      - ./keycloak-data:/opt/keycloak/data
      - ./keycloak-theme:/opt/keycloak/themes/rgi:ro
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"


  redis:
    container_name: ticket-booking-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    # Optional: keep the cache if the container restart
    command: redis-server --save 60 1 --loglevel warning
