services:
  localstack:
    container_name: ticket-booking-aws
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,sqs,stepfunctions,sts,iam
      - DEBUG=1
      - AWS_DEFAULT_REGION=sa-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./setup-aws.sh:/etc/localstack/init/ready.d/setup-aws.sh"
      - "./workflow-definition.json:/etc/localstack/init/ready.d/workflow-definition.json"

  keycloak:
    container_name: ticket-booking-auth
    image: quay.io/keycloak/keycloak:26.1.0
    volumes:
      - ./keycloak-data:/opt/keycloak/data
      - ./keycloak-theme:/opt/keycloak/themes/rgi:ro
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"

  redis:
    container_name: ticket-booking-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    # Optional: keep the cache if the container restart
    command: redis-server --save 60 1 --loglevel warning

#  aspire-dashboard:
#    container_name: aspire-dashboard
#    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
#    environment:
#      - ASPIRE_ALLOW_UNSECURED_TRANSPORT=true
#      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
#    ports:
#      - "18888:18888"
#      - "4317:18889"

#  jaeger-dashboard:
#    container_name: jaeger-dashboard
#    image: jaegertracing/all-in-one:latest
#    environment:
#      - COLLECTOR_OTLP_ENABLED=true
#    ports:
#      - "16686:16686"
#      - "4318:4318"
#      - "4317:4317"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234
    depends_on:
      - prometheus
      - loki
