### Variáveis
@url = http://localhost:5070/api/tickets

###
POST {{url}}/confirm
Content-Type: application/json

{
  "eventId": "rock-in-rio",
  "ticketId": "A1-VIP",
  "userId": "not-a-user"
}

###
POST {{url}}/reserve
Content-Type: application/json

{
    "eventId": "rock-in-rio",
    "ticketId": "A1-VIP",
    "userId": "not-a-user"
}

###
POST {{url}}/reserve
Content-Type: application/json

{
  "eventId": "rock-in-rio",
  "ticketId": "B52-GA",
  "userId": "not-a-user"
}

###
POST {{url}}/reserve
Content-Type: application/json

{
    "eventId": "rock-in-rio",
    "ticketId": "X42-GA",
    "userId": "not-a-user"
}

###
POST {{url}}/reserve
Content-Type: application/json

{
  "eventId": "woodstock",
  "ticketId": "A1-VIP",
  "userId": "not-a-user"
}
