### Variáveis
@tickets = http://localhost:5070/api/tickets
@events = http://localhost:5070/api/events

### Create event 1
PUT {{events}}
Content-Type: application/json

{
  "eventId": "Rock In Rio",
  "totalTickets": "128"
}
### Create event 2
PUT {{events}}
Content-Type: application/json

{
  "eventId": "Woodstock",
  "totalTickets": "256"
}


###
POST {{tickets}}/reserve
Content-Type: application/json

{
    "eventId": "Rock In Rio",
    "ticketId": "2",
    "isVip": true,
    "userId": "not-a-user"
}

###
POST {{tickets}}/confirm
Content-Type: application/json

{
  "eventId": "Rock In Rio",
  "ticketId": "2"
}

###
POST {{tickets}}/reserve
Content-Type: application/json

{
  "eventId": "Rock In Rio",
  "ticketId": "16",
  "isVip": false,
  "userId": "not-a-user"
}

###
POST {{tickets}}/confirm
Content-Type: application/json

{
  "eventId": "Rock In Rio",
  "ticketId": "16"
}

###
POST {{tickets}}/reserve
Content-Type: application/json

{
  "eventId": "Rock In Rio",
  "ticketId": "32",
  "isVip": false,
  "userId": "not-a-user"
}

###
POST {{tickets}}/reserve
Content-Type: application/json

{
  "eventId": "Rock In Rio",
  "ticketId": "64",
  "isVip": false,
  "userId": "not-a-user"
}

###
POST {{tickets}}/reserve
Content-Type: application/json

{
  "eventId": "Woodstock",
  "ticketId": "32",
  "isVip": true,
  "userId": "not-a-user"
}
